### ISSUE TITLE
Legacy NixOS installation

### ISSUE THREAD

**Issue by nis** [Cottand/leng#47]
I'm quite new to Nix, so this might be me doing something wrong.

This line:
`(builtins.getFlake "github:cottand/leng/1.5.0").nixosModules.default `

Gave me an error:
`       error: unable to download 'https://api.github.com/repos/cottand/leng/commits/1.5.0': HTTP error 422

       response body:

       {
         "message": "No commit found for SHA: 1.5.0",
         "documentation_url": "https://docs.github.com/rest/commits/commits#get-a-commit"
       }
`

If I change the import to `v1.5.0` instead of `1.5.0`:
`(builtins.getFlake "github:cottand/leng/v1.5.0").nixosModules.default`
I can install it and it seems to be running.

**Comment by Cottand** [comment]
hey @nis , thanks for catching that typo! You are correct, and I updated the docs accordingly now
