### ISSUE TITLE
Custom DNS records not working - authoritative DNS server required?

### ISSUE THREAD

**Issue by Lemmmy** [Cottand/leng#52]
Hello! I'm currently trying out leng as a replacement for pihole. It was fairly easy to set up, but I'm running into problems with custom DNS records on Windows.

## With leng

With the following customdnsrecords:

```toml
customdnsrecords = [
  "episode.             IN A 10.0.2.1",
]
```

I get the following response from `dig`:

```
; <<>> DiG 9.16.28 <<>> episode
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 14289
;; flags: qr rd; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 0
;; WARNING: recursion requested but not available

;; QUESTION SECTION:
;episode.                       IN      A

;; ANSWER SECTION:
episode.                3600    IN      A       10.0.2.1

;; Query time: 0 msec
;; SERVER: 10.0.2.1#53(10.0.2.1)
;; WHEN: Sat Jan 20 18:21:18 GMT Standard Time 2024
;; MSG SIZE  rcvd: 48
```

And the following response from `nslookup`:

```
Server:  UnKnown
Address:  10.0.2.1

Non-authoritative answer:
Name:    episode
Addresses:  10.0.2.1
          10.0.2.1
```

This _looks_ fine, until trying to use any other program on Windows, such as `ping`:

```
PS C:\Users\drew> ping episode
Ping request could not find host episode. Please check the name and try again.
```

## With pihole

On the other hand, pihole returns the following response with `dig` (ignore the IP addresses being different):

```
; <<>> DiG 9.16.28 <<>> episode @10.0.2.3
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 48260
;; flags: qr aa rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 1232
;; QUESTION SECTION:
;episode.                       IN      A

;; ANSWER SECTION:
episode.                0       IN      A       10.0.1.5

;; Query time: 2 msec
;; SERVER: 10.0.2.3#53(10.0.2.3)
;; WHEN: Sat Jan 20 18:23:08 GMT Standard Time 2024
;; MSG SIZE  rcvd: 52
```

(notice the additional `aa` and `ra` flags)

And `nslookup`:

```
Server:  pi.hole
Address:  10.0.2.3

Name:    episode
Address:  10.0.1.5
```

The biggest difference I can see is that pihole gives an authoritative response for this local DNS entry, whereas leng does not. I'm not an expert though so I'm not 100% sure this is the problem. Is this an issue with leng/anything I can work around?

**Comment by Lemmmy** [comment]
Apologies for the confusion, I had a core misunderstanding about how DNS resolution with no TLDs worked - it was using mDNS which is why it worked for some domains and not others

**Comment by Cottand** [comment]
hi @Lemmmy ! Thanks for posting your solution. 

I have never used mDNS, would you mind describing what exactly was the scenario in which PiHole worked and Leng didn't? Was it actually the `aa` flag?

I also did not fully understand why you had to hardcode your DNS record in `/etc/resolv.conf`. Could you not just set `episode.local. IN A 10.0.2.1` in the Leng config?

**Comment by Lemmmy** [comment]
Hi Cottand,

It might have been a coincidence that it was working when I was using pihole. Both DNS servers are happy to resolve the domain without `.local`, but Windows never even attempts to ask the DNS server for this information when performing a lookup. It will, however, work if there is a hardcoded entry in the OS's hosts file. I don't think the `aa` flag had anything to do with it in the end, it was just the only difference I could see from `dig`/`nslookup` outputs.

I think I wasn't clear with `/etc/resolv.conf`. I just had to add `local` as a search domain like so:

```
search local
nameserver 10.0.2.1
nameserver 10.0.2.2
```

And simply `episode.local. IN A 10.0.2.1` works as mentioned. Now when trying to resolve `episode`, Windows asks the DNS server for `episode.local.`, and everything works.

**Comment by Cottand** [comment]
Thanks for the detailed explanation - glad you could sort it out
